<?php

namespace Database\Seeders;

use App\Models\Branch;
use App\Models\Employee;
use Illuminate\Database\Seeder;

class EmployeeSeeder extends Seeder
{
    /**
     * PRASYARAT: BranchSeeder harus sudah dijalankan lebih dulu
     * (butuh branch "Haoyou Educator" untuk relasi branch_id).
     */
    public function run(): void
    {
        $branch = Branch::where('name', 'Haoyou Educator')->firstOrFail();

        // ============================================================
        // TODO: ganti seluruh data di bawah dengan data karyawan asli.
        // Contoh 2 baris ini hanya acuan format (1 tetap, 1 part time).
        // employee_code harus unik per karyawan.
        // ============================================================
        $employees = [
            [
                'employee_code' => 'EMP0001',
                'full_name' => 'Joy Limmunandar',
                'gender' => 'laki-laki',
                'nationality' => 'Indonesia',
                'religion' => 'Katolik',
                'blood_type' => 'O',
                'birth_place' => 'Malang',
                'birth_date' => '1990-01-01',
                'marital_status' => 'menikah',
                'last_education' => 'S1',
                'phone' => '085954537553',
                'email' => 'owner@haoyoueducator.com',
                'address' => 'Alamat lengkap owner',
                'position' => 'Owner',
                'employee_type' => 'tetap',
                'join_date' => '2023-01-01',
                'nik' => '0000000000000000',
            ],
            [
                'employee_code' => 'EMP0002',
                'full_name' => 'Rina Dwi Suciati',
                'gender' => 'perempuan',
                'nationality' => 'Indonesia',
                'religion' => 'Islam',
                'blood_type' => 'AB',
                'birth_place' => 'Pasuruan',
                'birth_date' => '1998-12-24',
                'marital_status' => 'belum_menikah',
                'last_education' => 'SMA',
                'phone' => '085822745398',
                'email' => 'rinaads853@gmail.com',
                'address' => 'Jalan Kapten Mulyono',
                'position' => 'Admin',
                'employee_type' => 'tetap',
                'join_date' => '2026-04-09',
                'nik' => '3514116412980001',
            ],
            [
                'employee_code' => 'EMP0003',
                'full_name' => 'Uziel Filadela Kustiawan',
                'gender' => 'perempuan',
                'nationality' => 'Indonesia',
                'religion' => 'Kristen',
                'blood_type' => 'O',
                'birth_place' => 'Malang',
                'birth_date' => '2004-07-01',
                'marital_status' => 'belum_menikah',
                'last_education' => 'S1',
                'phone' => '081528773979',
                'email' => 'uzielfiladelakustiawan@gmail.com',
                'address' => 'Jalan Kauman 3 No. 44, Malang',
                'position' => 'Admin',
                'employee_type' => 'tetap',
                'join_date' => '2026-08-12',
                'nik' => '3507314107040003',
            ],
            
        [
                'employee_code' => 'EMP0004',
                'full_name' => 'Teresa Liaunardo Tju',
                'gender' => 'perempuan',
                'nationality' => 'Indonesia',
                'religion' => 'Katolik',
                'blood_type' => null,
                'birth_place' => 'Jakarta',
                'birth_date' => '2007-03-14',
                'marital_status' => 'belum_menikah',
                'last_education' => 'S1',
                'phone' => '08816173529',
                'email' => null,
                'address' => 'Sigura Gura 4',
                'position' => 'Teacher',
                'employee_type' => 'part_time',
                'join_date' => '2026-05-05',
                'nik' => '3172055403070005',
            ],

            [
                'employee_code' => 'EMP0005',
                'full_name' => 'Vanessa Tan',
                'gender' => 'perempuan',
                'nationality' => 'Indonesia',
                'religion' => 'Budha',
                'blood_type' => null,
                'birth_place' => 'Pekanbaru',
                'birth_date' => '2007-08-24',
                'marital_status' => 'belum_menikah',
                'last_education' => 'S1',
                'phone' => '087816276207',
                'email' => null,
                'address' => 'Jl. Kerto Asri Dalam, No 122A',
                'position' => 'Teacher',
                'employee_type' => 'part_time',
                'join_date' => '2026-08-11',
                'nik' => '1471096408070001',
            ],

            [
                'employee_code' => 'EMP0006',
                'full_name' => 'Natalia Repiuli Dertina Sitorus',
                'gender' => 'perempuan',
                'nationality' => 'Indonesia',
                'religion' => 'Kristen',
                'blood_type' => null,
                'birth_place' => 'Lamparinga',
                'birth_date' => '2007-12-18',
                'marital_status' => 'belum_menikah',
                'last_education' => 'S1',
                'phone' => '082195354707',
                'email' => null,
                'address' => 'Sulawesi Tenggara',
                'position' => 'Teacher',
                'employee_type' => 'part_time',
                'join_date' => '2026-05-04',
                'nik' => '7409035812070001',
            ],

            [
                'employee_code' => 'EMP0007',
                'full_name' => 'Kezia Sophi Adventa Ratta',
                'gender' => 'perempuan',
                'nationality' => 'Indonesia',
                'religion' => 'Kristen Protestan',
                'blood_type' => null,
                'birth_place' => 'Bekasi',
                'birth_date' => '2005-12-02',
                'marital_status' => 'belum_menikah',
                'last_education' => 'S1',
                'phone' => '081938798913',
                'email' => null,
                'address' => 'Jalan Taman Borobudur Kencana 1 No 26',
                'position' => 'Teacher',
                'employee_type' => 'part_time',
                'join_date' => '2026-07-24',
                'nik' => '3201074212050005',
            ],

            [
                'employee_code' => 'EMP0008',
                'full_name' => 'Marsya Amelia',
                'gender' => 'perempuan',
                'nationality' => 'Indonesia',
                'religion' => 'Islam',
                'blood_type' => null,
                'birth_place' => 'Mojokerto',
                'birth_date' => '2006-09-18',
                'marital_status' => 'belum_menikah',
                'last_education' => 'S1',
                'phone' => '088805477868',
                'email' => null,
                'address' => 'Jl. MT. Haryono, Gg. 6c No. 858, Dinoyo',
                'position' => 'Teacher',
                'employee_type' => 'part_time',
                'join_date' => '2026-07-02',
                'nik' => '3516055809060001',
            ],
            [
                'employee_code' => 'EMP0009',
                'full_name' => 'Nathania Jovita',
                'gender' => 'perempuan',
                'nationality' => 'Indonesia',
                'religion' => 'Buddha',
                'blood_type' => null,
                'birth_place' => 'Pekanbaru',
                'birth_date' => '2007-05-05',
                'marital_status' => 'belum_menikah',
                'last_education' => null,
                'phone' => '081275530745',
                'email' => null,
                'address' => 'Jl. Kerto Asri No. 122A',
                'position' => 'Teacher',
                'employee_type' => 'part_time',
                'join_date' => '2026-06-12',
                'nik' => '1471044505070022',
            ],
            [
                'employee_code' => 'EMP0010',
                'full_name' => 'Achmad Arif Deni',
                'gender' => 'laki_laki',
                'nationality' => 'Indonesia',
                'religion' => 'Islam',
                'blood_type' => 'A',
                'birth_place' => 'Malang',
                'birth_date' => '1989-11-26',
                'marital_status' => 'belum_menikah',
                'last_education' => 'SMK',
                'phone' => '08983442709',
                'email' => 'ahmad.forcesmith.deni956@gmail.com',
                'address' => 'Jl.Satsui Tubun 1/ 45',
                'position' => 'Cleaning Service',
                'employee_type' => 'tetap',
                'join_date' => '2025-08-05',
                'nik' => '3573042611890005',
            ], 

            [
                'employee_code' => 'EMP0011',
                'full_name' => 'Fitri Maulidah',
                'gender' => 'perempuan',
                'nationality' => 'Indonesia',
                'religion' => 'Islam',
                'blood_type' => 'B',
                'birth_place' => 'Trenggalek',
                'birth_date' => '1998-07-12',
                'marital_status' => 'belum_menikah',
                'last_education' => 'S1',
                'phone' => '081946728321',
                'email' => 'maulfi590@gmail.com',
                'address' => 'RT 22 RW 04 Dusun Madatan Desa Panggul Kecamatan Panggul Kabupaten Trenggalek',
                'position' => 'Teacher',
                'employee_type' => 'tetap',
                'join_date' => '2026-02-02',
                'nik' => '3503015207970005',
            ],

            [
                'employee_code' => 'EMP0012',
                'full_name' => 'Deva Selviana',
                'gender' => 'perempuan',
                'nationality' => 'Indonesia',
                'religion' => 'Islam',
                'blood_type' => 'B',
                'birth_place' => 'Kediri',
                'birth_date' => '2004-12-28',
                'marital_status' => 'belum_menikah',
                'last_education' => 'SMA',
                'phone' => '085791357577',
                'email' => 'selvianadeva8@gmail.com',
                'address' => 'Jl Pandan Surat RT05 RW01 Banyuanyar, Gurah, Kediri',
                'position' => 'Course Consultant',
                'employee_type' => 'tetap',
                'join_date' => '2026-07-07',
                'nik' => '3506106812040001',
            ],

            [
                'employee_code' => 'EMP0013',
                'full_name' => 'Eka Putri Natalya Kabelen',
                'gender' => 'perempuan',
                'nationality' => 'Indonesia',
                'religion' => 'Islam',
                'blood_type' => 'O',
                'birth_place' => 'Nganjuk',
                'birth_date' => '2004-12-25',
                'marital_status' => 'belum_menikah',
                'last_education' => 'D4',
                'phone' => '085232021239',
                'email' => 'natalyakabelen2512@gmail.com',
                'address' => 'Perumahan Griya Shanta Blok K.250',
                'position' => 'Course Consultant',
                'employee_type' => 'tetap',
                'join_date' => '2026-07-06',
                'nik' => '3506106812040001',
            ],

            [
                'employee_code' => 'EMP0014',
                'full_name' => 'Isnaeny Tri Larassati',
                'gender' => 'perempuan',
                'nationality' => 'Indonesia',
                'religion' => 'Islam',
                'blood_type' => null,
                'birth_place' => 'Malang',
                'birth_date' => '2004-07-02',
                'marital_status' => 'belum_menikah',
                'last_education' => null,
                'phone' => '085826195940',
                'email' => 'isnaenytrilarassati1@gmail.com',
                'address' => 'Gedangan Rt: 03/Rw :01, Gondowangi, Wagir',
                'position' => 'Course Consultant',
                'employee_type' => 'tetap',
                'join_date' => '2026-07-06',
                'nik' => '3506106812040001',
            ],

            [
                'employee_code' => 'EMP0015',
                'full_name' => 'Dwi Ayu Wulandari',
                'gender' => 'perempuan',
                'nationality' => 'Indonesia',
                'religion' => 'Islam',
                'blood_type' => 'O',
                'birth_place' => 'Malang',
                'birth_date' => '1995-12-16',
                'marital_status' => 'belum_menikah',
                'last_education' => 'S1',
                'phone' => '085857418637',
                'email' => 'dwiayuw04@gmail.com',
                'address' => 'Jl. Kopda Sukoco RT 17 RW 01 Wonokerto Kec Bantur',
                'position' => 'Teacher',
                'employee_type' => 'tetap',
                'join_date' => '2026-07-08',
                'nik' => '3506106812040001', 
            ],

            [
                'employee_code' => 'EMP0016',
                'full_name' => 'Febry Andrias',
                'gender' => 'laki_laki',
                'nationality' => 'Indonesia',
                'religion' => 'Islam',
                'blood_type' => 'O',
                'birth_place' => 'Malang',
                'birth_date' => '2004-06-09',
                'marital_status' => 'belum_menikah',
                'last_education' => 'SMA',
                'phone' => '089513080742',
                'email' => 'febryandrias734@gmail.com',
                'address' => 'Dusun Pilang, RT 005 RW 014, Sidodadi, Lawang, Malang',
                'position' => 'Course Consultant',
                'employee_type' => 'tetap',
                'join_date' => '2026-08-12',
                'nik' => '3506106812040001',
            ],

        ];

        foreach ($employees as $data) {
            Employee::updateOrCreate(
                ['employee_code' => $data['employee_code']],
                array_merge($data, ['branch_id' => $branch->id])
            );
        }
    }
}